name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: bash test_install
